### ISSUE TITLE
cimgui.cpp:1126:36:error: 'sprintf_s' was not declared in this scope

### ISSUE THREAD

**Issue by ScottHuangZL** [Gekkio/imgui-rs#1]
Win7 64bit, Rust 1.2 stable 32bit, failed build imgui-rs.  Can you help on it? Thanks.

**Comment by ScottHuangZL** [comment]
Hi Gekkio, Can you fix it ASAP? Thanks.

**Comment by Gekkio** [comment]
Hmm, this looks like a portability issue in the cimgui project, so I can't probably fix it in imgui-rs. Let's open an issue in cimgui once we know what the problem is.

Firstly, I need to understand what kind of c/c++ development tools you have installed. Do you have mingw and/or visual studio installed? If yes, what are the versions? Try running `g++ --version` and `cl`. 

Secondly, could you please send the output of `cargo build --verbose` ? It's a lot of text but it might tell us more about how the c++ compiler is executed in the build.

**Comment by ScottHuangZL** [comment]
Hello, I am upgrade the rust to nightly 1.4 version. and also download mingw64 4.92 version. 
After that, the compile job able complete even get some warning.
Thanks.
