### ISSUE TITLE
Hovering windows problem ? 

### ISSUE THREAD

**Issue by Catvert** [Gekkio/imgui-rs#159]
Hi !
I have a problem that seems specific to this binding.  The imgui_sys method igIsAnyWindowHovered() returns false even if the cursor is above the window if and only if the window has not been "clicked" beforehand. There is a kind of focus system (the title bar turns black if I select another window or click in the void) that operates and which also prevents the interface elements from being highlighted if the window is not "focus" (which is not present in the original version of imgui if I'm not mistaken). Is there any way to disable this system?  The problem may be due to the configuration of my project  but I don't think; I followed the examples to configure it. This problem prevents me from checking if the interface is hovered or not, which is quite annoying for a level editor.

![screenshot_20180919_214756](https://user-images.githubusercontent.com/8643204/45777344-d49b7500-bc55-11e8-951d-a52954a0ac20.png)
Note : In this example, igIsAnyWindowHovered return false and the slider float is not highlighted.

Thanks for your help !

**Comment by Gekkio** [comment]
In general, if you suspect the bindings are doing something wrong, one way to debug the issue is to see if you can replicate the problem by comparing imgui-rs `test_window` (and maybe `test_window_impl`) and one of the upstream examples. I tried this and didn't see any problems so it might be an issue in your configuration/support code.

> There is a kind of focus system (the title bar turns black if I select another window or click in the void) that operates

This is normal imgui behaviour and you can see this with the upstream C++ examples.

> which also prevents the interface elements from being highlighted if the window is not "focus"

This doesn't seem to be normal behaviour, but I couldn't replicate the problem. In imgui-rs `test_window`, even if I click outside the window to remove the focus, hovering widgets still has a "hover" highlight.

Could you check if the imgui-rs `test_window` example has these issues on your machine?

**Comment by Catvert** [comment]
Hi !
I've check tried the test_window example and it work. I've found my issue, it wasn't updating the mouse every frame but only when an event occurred.
Sorry for the inconvenience.
