### ISSUE TITLE
gfx-renderer macOS GLSL version 130 problems

### ISSUE THREAD

**Issue by PJB3005** [Gekkio/imgui-rs#170]
I'm trying to run imgui-gfx-renderer on this 10 year old macbook pro (I know right?). It does support all the way up to OpenGL 3.3, but for some reason on a 3.3 context, `#version 130` of GLSL is not supported. `#version 140`, `150` and `330` all work, just not `130`.

Problem is that `imgui-gfx-renderer` only provides a `130` shader version for all of OpenGL 3+.

So.. I can't run the gfx renderer (I can on a compatibility profile but the rest of this program relies on a core profile so..)

I recompiled the crate with a version 150 shader and the program loaded up just fine.

So would it be possible to provide a shaders version using a higher GLSL version? Pretty sure it'd fix the problem.

**Comment by Gekkio** [comment]
Sure, this sounds like a doable idea. While supporting 10 year old stuff isn't top priority, in this case it's very simple and doesn't do any harm so let's do it :smile: 

I think I'll add version 150 shaders, because OpenGL 3.2 / GLSL 1.50 added the core/compatibility profile split, which is a major change and sounds like a good version to have explicit support for.

**Comment by PJB3005** [comment]
Works like a charm!
