### ISSUE TITLE
is_item_hovered and ImGuiHoveredFlags

### ISSUE THREAD

**Issue by agersant** [Gekkio/imgui-rs#186]
In the C++ version of imgui, `ImGui::IsItemHovered` accepts a flags argument to support various modifiers. With imgui-rs, I believe these flags can be used when calling `igIsItemHovered` from imgui-sys, but that is unsafe.

Would there be interest in a PR adding `is_item_hovered_with_flags` or a similar safe wrapper in imgui-rs?

**Comment by agersant** [comment]
Here is the PR in case there's any interest: https://github.com/Gekkio/imgui-rs/pull/189

**Comment by Gekkio** [comment]
This is a good thing to have and I've merged the PR :smiley:
However, I just want to point out that I'm in general very cautious about adding new APIs that are just pass-through functions for the raw API, because there's a lot of safety-related landmines and the raw APIs often let you do "invalid" things.

We can now make these function calls (+ of course various combinations of flags too):

```rust
ui.is_window_hovered_with_flags(ImGuiHoveredFlags::ChildWindows);
ui.is_window_hovered_with_flags(ImGuiHoveredFlags::RootWindow);
ui.is_window_hovered_with_flags(ImGuiHoveredFlags::AnyWindow);
ui.is_window_hovered_with_flags(ImGuiHoveredFlags::AllowWhenBlockedByPopup);
ui.is_window_hovered_with_flags(ImGuiHoveredFlags::AllowWhenBlockedByActiveItem);
ui.is_window_hovered_with_flags(ImGuiHoveredFlags::AllowWhenOverlapped);
ui.is_window_hovered_with_flags(ImGuiHoveredFlags::AllowWhenDisabled);
ui.is_window_hovered_with_flags(ImGuiHoveredFlags::RectOnly);
ui.is_window_hovered_with_flags(ImGuiHoveredFlags::RootAndChildWindows);

ui.is_item_hovered_with_flags(ImGuiHoveredFlags::ChildWindows);
ui.is_item_hovered_with_flags(ImGuiHoveredFlags::RootWindow);
ui.is_item_hovered_with_flags(ImGuiHoveredFlags::AnyWindow);
ui.is_item_hovered_with_flags(ImGuiHoveredFlags::AllowWhenBlockedByPopup);
ui.is_item_hovered_with_flags(ImGuiHoveredFlags::AllowWhenBlockedByActiveItem);
ui.is_item_hovered_with_flags(ImGuiHoveredFlags::AllowWhenOverlapped);
ui.is_item_hovered_with_flags(ImGuiHoveredFlags::AllowWhenDisabled);
ui.is_item_hovered_with_flags(ImGuiHoveredFlags::RectOnly);
ui.is_item_hovered_with_flags(ImGuiHoveredFlags::RootAndChildWindows);
```

And here's the problem: some of these crash the process with abort (not a panic which would give a backtrace), so I don't think this is a particularly good API. Some things are "forbidden" but the API doesn't reflect that. It's not the end of the world right now, but in 0.1 I'm planning to have a closer look at APIs like this and redesign them.

**Comment by agersant** [comment]
Thanks for the insight, I wasn't aware of that ImGui quirk. I just took a look at the source and the forbidden combinations are:

- IsWindowHovered with AllowWhenOverlapped
- IsItemHovered with RootWindow or ChildWindows

I can see two solutions, one would be to split the ImGuiHoveredFlags into two Rust enums (one for windows, one for items). The other would be to zero out the dangerous flags in the safe wrapper. I'm happy to implement one of these solutions as a follow-up to the PR.

Cheers!

**Comment by Gekkio** [comment]
Closing since these functions got a slight overhaul in 0.2. I ended up splitting the flags into two Rust enums as suggested here.
