### ISSUE TITLE
Maintaining state on widgets

### ISSUE THREAD

**Issue by wdevore** [Gekkio/imgui-rs#202]
Hi,

I am new to imgui-rs. I have been trying to figure out why my checkbox won't maintain state. I am using the example `hello_gfx.rs` and added a simple checkbox:

```
    let mut cb = false;

    ui.window(...)
       .build(|| {
       ...
       cb = ui.checkbox(im_str!("check box"), &mut cb);
       }
```

But the checkbox won't stayed checked. It just flickers and returns to unchecked.
I can set `cb` to true and it will stay checked. Basically it won't toggle.

Any idea what I am doing wrong?

Thanks

**Comment by Gekkio** [comment]
It seems to me that there's two problems with your code:

1. You're mixing the checkbox state with the event "was the checkbox clicked"

The return value of `ui.checkbox` is a boolean that is true when the checkbox was clicked during that frame. You shouldn't assign it to the actual state that is supposed to contain the checkbox value.

2. `cb` seems to be a variable that has a lifecycle of one frame

The UI code gets called every frame, and it looks like `let mut cb = false` is just a local stack variable. This means that there's nothing that persists the state between frames, because you're literally starting every frame with a fresh `false` value.

Try something like this:

```rust
    let mut cb = false; // this variable has a lifecycle longer than one frame
    support_gfx::run("hello_gfx.rs".to_owned(), CLEAR_COLOR, |ui| {
        // this function gets called every frame
        ui.window(im_str!("My window"))
           .build(|| {
               let was_clicked = ui.checkbox(im_str!("check box"), &mut cb);
               if was_clicked {
                 println!("Checkbox was clicked");
               }
           });
        true
    });
```

**Comment by wdevore** [comment]
Ahhh! I didn't realize that the `::run` was being called on every frame. I thought just `ui.window` was. That make sense now. Thanks.
