### ISSUE TITLE
glium examples are broken

### ISSUE THREAD

**Issue by hamaluik** [Gekkio/imgui-rs#214]
When trying to compile any of the glium examples, the versioning is broken. Specifically, Cargo includes and builds both `winit 0.18.1` and `winit 0.19.1`:

```
   Compiling winit v0.18.1
   Compiling winit v0.19.1
```

Which leads to errors:

```
error[E0308]: mismatched types
  --> examples/support/mod.rs:70:17
   |
70 |                 &event,
   |                 ^^^^^^ expected enum `winit::events::Event`, found a different enum `winit::events::Event`
   |
   = note: expected type `&winit::events::Event` (enum `winit::events::Event`)
              found type `&winit::events::Event` (enum `winit::events::Event`)
note: Perhaps two different versions of crate `winit` are being used?
  --> examples/support/mod.rs:70:17
   |
70 |                 &event,
   |                 ^^^^^^
```

Similar to #196 however, the issue is that in this repo, the [`Cargo.lock`](https://github.com/Gekkio/imgui-rs/blob/master/imgui-glium-examples/Cargo.lock) file specifies to use `winit 0.18.1` everywhere. If you don't have this `Cargo.lock` file, you'll get `glutin 0.19.0` using `winit 0.18.1` and `imgui-winit-support 0.0.24-pre` using `winit 0.19.1`.

I'm not sure how to fix this without editing the lock file, which is not an ideal solution..

**Edit**: I can fix this by downgrading all the imgui crates to `0.0.22`.

**Comment by Gekkio** [comment]
Unfortunately there's no way to fix this and manual editing of the lock file is needed as a workaround, because Cargo doesn't support "public dependencies" (somewhat similar to peer dependencies in npm). Once https://github.com/rust-lang/rust/issues/44663 is fixed, this won't be an issue any more. Also, the recent upgrade to glium 0.24 removes this issue for the moment (because glium 0.24 pulls winit 0.19), but the problem will surely appear again once winit dependency versions drift apart a bit between gfx and glium.

The basic problem is that imgui-winit-support declares support for winit `>= 0.16, <= 0.19`, but if you have a project that depends on imgui-winit-support, Cargo will always pull the highest possible version (0.19). This happens even if another version of winit is already in the project (for example, winit 0.18 is pulled by glium 0.23), so you end up with two incompatible versions. And we can't lower the supported version because winit 0.19 is the latest version and gfx-rs wants it. There's simply no way for imgui-winit-support to support both glium and gfx-rs at the same time without any problems.

The current solution is not optimal, but seems to be the only possible way to make it work right now: declare a wide supported version range in imgui-winit-support, but edit the lockfile in the user project to force Cargo to use the existing winit version and not pull 0.19.

**Comment by hamaluik** [comment]
That's unfortunate, but thanks for the answer!
