### ISSUE TITLE
Rough idea for automatically-generated docs

### ISSUE THREAD

**Issue by jeffvandyke** [Gekkio/imgui-rs#227]
I'm new to imgui, but docs seem to be a desired addition, including for me, and it'd be great if they were automatically generated. I'm banging my head around [cimgui](https://github.com/cimgui/cimgui)'s generator Lua files, having never used Lua before, but I think I should be able to get function documentation from `imgui/imgui.h` at least inside the `generator/output/definitions.json` file, which could be used to generate function comments for the .rs files.

Am I on the right track with this? Would this help imgui-rs get docs? Any ideas/pointers?

**Comment by Gekkio** [comment]
It's an interesting idea! However, this would only help to generate docs for imgui-sys so it's not very useful for most users. The main imgui crate needs handwritten docs, because the API is slightly different and upstream documentation might not make sense in this context.

I think having imgui-sys documented is still a good thing to have if generating it would be easy...

**Comment by jeffvandyke** [comment]
Gotcha. Maybe that would take higher priority before trying modifying the generation script.
