### ISSUE TITLE
call imgui_sys from ui ?

### ISSUE THREAD

**Issue by michelson** [Gekkio/imgui-rs#23]
Hi, 

is possible to call `ig` from imgui_sys from ui interface. something like: 

```rust
            if ui.collapsing_header(im_str!("Menu")).build() {
                ui.imgui::igNextColumn(); // <-- this
                show_user_guide(ui);
            }
```
BTW, I've sent a Pull Request that implements columns methods

best

**Comment by Gekkio** [comment]
The raw and unsafe imgui_sys functions are not exported from imgui, because I don't want to encourage people to mix safe and unsafe APIs except when absolutely necessary.

What you can do is:

* Add imgui-sys dependency to Cargo.toml
* Add `extern crate imgui_sys`
* Call any imgui_sys functions anywhere, if you are 100% sure you know what you are doing and you are not violating any rules
