### ISSUE TITLE
Implement io::Write or fmt::Write for ImString

### ISSUE THREAD

**Issue by yanchith** [Gekkio/imgui-rs#290]
Hello, thank you for working on imgui-rs :heart: 

Ran into the following today:

I have a type that implements `Display` and I want to render that display into a preallocated `ImString` without allocating an intermediate buffer. Unfortunately, `ImString` does not implement `io::Write` nor `fmt::Write` required for `std::write` or `std::fmt::write`.

Judging from `std` impl on `String`, `fmt::Write` should be easy to add:

```rust
#[stable(feature = "rust1", since = "1.0.0")]
impl fmt::Write for String {
    #[inline]
    fn write_str(&mut self, s: &str) -> fmt::Result {
        self.push_str(s);
        Ok(())
    }

    #[inline]
    fn write_char(&mut self, c: char) -> fmt::Result {
        self.push(c);
        Ok(())
    }
}
```

Happy to contribute this myself, if you agree with the change.

**Comment by Gekkio** [comment]
This is a good idea! `fmt::Write` has now been added in https://github.com/Gekkio/imgui-rs/commit/5ea969d273dc7dddcaca71ae9e6fd861f412147e

Implementing `io::Write` would not be ok, because it operates with raw bytes and could violate the contract of ImString. But `fmt::Write` is enough for `write!` so this use case should be covered now :slightly_smiling_face:
