### ISSUE TITLE
example without glium

### ISSUE THREAD

**Issue by erethedaybreak** [Gekkio/imgui-rs#49]
Hello,

Could you please add an example how to initialize this properly without glium?

I have a glutin window, and I saw in `imgui-example/example/support/mod.rs` at `Support::render()` that I should be doing something like this:

        let size_points = window.get_inner_size_points().unwrap();
        let size_pixels = window.get_inner_size_pixels().unwrap();

        let ui = self.imgui.frame(size_points, size_pixels, delta_s);

        run_ui(&ui);

        self.renderer.render(&mut target, ui).unwrap();

When I try the equivalent where `window` is a `glutin::Window`, at `imgui.frame()` I get this error:

```
third-party/cimgui/imgui/imgui.cpp:2047: void ImGui::NewFrame(): Assertion `g.IO.Fonts->Fonts.Size > 0' failed.
```

Apparently I should initialize the fonts somehow, a non-glium (glutin only) example would be great help.

**Comment by Gekkio** [comment]
Are you writing a custom renderer? That's quite a lot of work :sweat_smile:
I'll think about writing an example, but it's a bit tricky because a runnable example would have no visible output without an actual implementation of a renderer. But at least I could provide some extra documentation about this topic. Here's a quick summary:

These steps are needed at initialization time:

* Initialize the library: `let mut imgui = ImGui::init()`
* Prepare a font texture by calling `imgui.prepare_texture`. You need to provide a callback that will receive a TextureHandle which contains the texture width, height, and a slice of raw pixel data. It's your responsibility to store the pixel data correctly so that you can use it later in the frame renderer. [Here's how imgui-glium-renderer does this](https://github.com/Gekkio/imgui-rs/blob/master/imgui-glium-renderer/src/lib.rs#L176)
* (call imgui.set_texture_id to store an abritrary numerical identifier of the font texture. This is not needed, but is provided for convenience so you can later recognize this texture in your frame renderer)

These steps are needed during each frame:

* Start a frame by calling `let ui = imgui.frame(...)`
* Construct your UI
* Call `ui.render`. You need to provide a render callback that receives a `&Ui` reference and a raw `DrawList` which you must render. Basically, you upload the vertex and index buffers, and then loop each element in the command buffer and render it using the given texture, clip rectangle, and index buffer slice. The relevant index slice is not provided directly and you need to calculate it yourself by tracking the element counts (e.g. let's say first command has count 5, second has count 3. First index buffer slice is 0..5, second is 5..(5+3))

**Comment by erethedaybreak** [comment]
Thanks for the notes! Yes, I thought I was just missing a few API calls. Better close this then, I'm sorry for the over-the-top request.
