### ISSUE TITLE
low-level glutin and/or gfx-rs support guidance

### ISSUE THREAD

**Issue by olsonjeffery** [Gekkio/imgui-rs#6]
Hi, I haven't dug into the codebase too much yet, but I see that sdl2 and glium are supported OOTB. I would be interested in seeing what it'd take to get this library to work with glutin and/or gfx-rs (tbh, I'm not sure what the boundary is for imgui, dependencies-wise, between the window/context stuff and actual opengl,etc interfaces like glium or gfx-rs.

If it's pretty straightforward, maybe I can just do a PR for it. But in any case, an opinion would be appreciated.

Thanks!

**Comment by Gekkio** [comment]
Hi, having more renderers would definitely make it easier to integrate imgui-rs with a wider variety of projects. There's basically three things needed to render the user interface:

1. Context/window creation, event loop
2. Handling events and passing information to ImGui
3. Taking vertex, index and command buffers from ImGui and doing rendering with them. Also, in the setup phase taking raw texture data from ImGui

The only things directly needed in imgui-rs are 2 and 3. The current SDL2 support is part of 2, while the glium support is part of 3. I think it was a genius idea in the original ImGui library to just output buffers, which makes integration extremely flexible.

So, since 1 is not needed, glutin support would only be related to 2. gfx-rs on the other hand would fit to 3, so you'd need to figure out how to render the buffers given by imgui-rs. I'm afraid I have no idea of the API of gfx-rs, so I can't give you any pointers. But you can take a look at `render` and `render_draw_list` functions in glium_renderer.rs for some ideas. I can also explain the glium code in more detail if that's useful.

I'd like to also point out that 2 is very much in progress at the moment. SDL2 support is very barebones, and only supports mouse events. I might end up removing it completely, since it might be easier to just expose functions to set state and let the library user call those directly. The example programs use glutin in this way (see examples/support/mod.rs).

**Comment by Gekkio** [comment]
gfx-rs support was merged in #44, so I'll close this issue.
