### ISSUE TITLE
Using custom textures

### ISSUE THREAD

**Issue by Palmr** [Gekkio/imgui-rs#65]
I was attempting to load a texture from my application into an imgui window using something similar to the following code:

```
ui.window(im_str!("PPU"))
    .size((150.0, 130.0), ImGuiSetCond_FirstUseEver)
    .resizable(true)
    .build(|| {
        unsafe {
            imgui_sys::igImage(ppu.get_tex_id(), ImVec2::new(160.0, 144.0), ImVec2::new(0.0, 0.0), ImVec2::new(1.0, 1.0), ImVec4::new(0.0, 0.0, 0.0, 1.0), ImVec4::new(1.0, 0.0, 0.0, 1.0));
        }
    });
```

But it seems custom textures are disallowed by the imgui-rs glium renderer: https://github.com/Gekkio/imgui-rs/blob/master/imgui-glium-renderer/src/lib.rs#L108

I'm wondering what needs to be done for this to get supported?

**Comment by Gekkio** [comment]
Yeah, this is something that isn't yet supported because designing it properly seems fairly difficult. The assert is there just to notify that the renderer doesn't know what to do with unknown texture IDs.

In your example, the renderer would have to somehow get the full texture object with the ID much later once rendering starts (with proper lifetime checks and all). Also, the main library can't depend on any renderer-specific concepts, types, or code, and the design should work well with both the glium and gfx renderers (+ any potential future ones, like GDI).

It's definitely not impossible to do, but requires some work.
